// EcologyEngine — Food chain sim: producers, prey, predators, decomposers; energy transfer; health score.
// Generated by the Counted Repo Factory (seeds/seeds.yaml). Deterministic by construction.
// Layout: docs/REPO_STANDARD.md — core logic in src/lib/, public API in src/index.ts.

import { seededRandom } from "./lib/rng";
import { EnergyTransfer, HealthScore } from "./lib/modules";

export const SPEC = "Food chain sim: producers, prey, predators, decomposers; energy transfer; health score.";
export const MODULES = [{ id: "FoodChain", name: "EcologyEngine :: FoodChain" }, { id: "EnergyTransfer", name: "EcologyEngine :: EnergyTransfer" }, { id: "HealthScore", name: "EcologyEngine :: HealthScore" }];
export { seededRandom };
export interface Population { producers: number; prey: number; predators: number; decomposers: number; }
export class FoodChain {
  private p: Population;
  private readonly rng: () => number;
  constructor(seed = 42) {
    this.rng = seededRandom(seed);
    this.p = { producers: 60, prey: 30, predators: 10, decomposers: 5 };
  }
  tick(): void {
    const r = () => Math.floor(this.rng() * 5) - 2;
    const p = this.p;
    p.producers = Math.max(5, Math.min(120, p.producers + r()));
    p.prey = Math.max(3, Math.min(100, p.prey + r() - (p.predators > 15 ? 1 : 0)));
    p.predators = Math.max(1, Math.min(60, p.predators + (p.prey > 20 ? 1 : -1)));
    p.decomposers = Math.max(1, Math.min(40, p.decomposers + (p.prey < 10 ? 1 : 0)));
  }
  healthScore(): number {
    const total = this.p.producers + this.p.prey + this.p.predators + this.p.decomposers;
    if (total === 0) return 0;
    const share = this.p.predators / total;
    const balance = 1 - Math.abs(share - 0.1);
    return Math.round(Math.max(0, Math.min(100, 60 + balance * 40)));
  }
  population(): Population { return { ...this.p }; }
  simulate(ticks: number): Population[] {
    const out: Population[] = [];
    for (let i = 0; i < ticks; i++) { this.tick(); out.push(this.population()); }
    return out;
  }
}
